### PR TITLE
Demo materials

### PR DESCRIPTION
**Pull request by sjordan29**
Hi @jrutyna and @aufdenkampe, 

I spent some time creating simple demo materials in the `examples` folder. I'd appreciate it if each of you could review and update the notebooks. Probably makes sense for you two to coordinate on when you review so that we don't have terrible merge conflicts with the notebooks. 

One question in particular I have is about referencing large data that is not stored on the repo anymore due to the issues with LFS. Should we add some larger models to some sort of data sharing platform and reference it in the notebooks so folks can run them if they want?

I updated the version number in the `__init__` so that we can issue a release when this is merged to main.

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@sjordan29, awesome! I'll take a look. I really like the idea of issuing a release early next week, before the webinar.

**Comment by jrutyna** [comment]
I propose not using the 5x10 grid in the "getting started notebook". I consider the hydraulics from the HEC-RAS model overly complicated for this simple test case. I suggest using the Sumwere Creek coarse mesh model for a short period of time in this "getting started notebook".

**Comment by sjordan29** [comment]
@aufdenkampe - updates made and ready for your review again.

**Comment by aufdenkampe** [comment]
@sjordan29, thanks! I'll review this morning.

**Comment by aufdenkampe** [comment]
This is looking good!

**Review by aufdenkampe — COMMENTED** [review]
Looks good! Thanks!

**Pull request merged**
